# About the site
title: Interdicta
tagline: Life without Pants!
description: Interdicta es una plataforma-red informativa sobre performance, performatividad e identidades críticas.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:
baseurl:
language: es

# Owner/author information
owner:
  name: Interdicta plataforma de performance
  avatar: logo.png
  bio: "Somos una plataforma-red informativa sobre performance, performatividad e identidades críticas, originada en Santiago de Chile, y proyectada en diferentes territorios, que respaldada por diversas colaboraciones busca promover alianzas e intercambios entre quienes están produciendo y reflexionando desde la(s) escena(s) local(es), zonas cuyo imaginario social viene atravesado por tensiones y disputas que han levantado la urgencia de construir distintos acuerdos estratégicos/fácticos, que apunten a la visualización de los procesos y espacios generados por la práctica de performance; la producción y difusión de encuentros, talleres y modalidades de formación como charlas y textos que apuntan a un proceso de documentación, crítica, y el establecimiento de enlaces entre interdictos, desobedientes, abyectos y curiosos."
  email: interdictaperformance@gmail.com
  twitter:
  facebook: interdictaplataformaperformancechile
  github:
  linkedin:
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
  - title: Interdicta
    url: /interdicta
  - title: Posicionamiento
    url: /posicionamiento
  - title: Visiones
    url: /visiones
  - title: Convocatoria
    url: /convocatorias/1a-convocatoria-manifiestos
  # - title: Manifiestos
  #   url: /theme-setup/
  # - title: Encuentros
  #   url: /technical-details/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: UTC
future: true
markdown: kramdown
permalink: /:categories/:title

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

include: [".htaccess"]
exclude: []

collections:
  aliados:
    output: true
    permalink: /:collection/:name/
