# About the site
title: Interdicta
tagline: Life without Pants!
description: An awesome Jekyll theme by Engineer Hossain Mohd Faysal featuring a slide out drawer navigation for mobile browsers.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:
baseurl:
language: es

# Owner/author information
owner:
  name: Interdicta plataforma de performance
  avatar: logo.png
  bio: ""
  email: interdictaperformance@gmail.com
  twitter:
  facebook: interdictaplataformaperformancechile
  github:
  linkedin:
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
  - title: Interdicta
    url: /
  - title: Convocatorias
    url: /about/
  - title: Visiones
    url: /visiones/
  - title: Manifiestos
    url: /theme-setup/
  - title: Encuentros
    url: /technical-details/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: UTC
future: true
markdown: kramdown
permalink: /:categories/:title

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

include: [".htaccess"]
exclude: []
